catalog:
  glade_plus_url:  http://elysium.elte.hu/~dalyag/GLADE+.txt
  glade24_url:     https://glade.elte.hu/GLADE-2.4.txt
  data_dir:        data/

skymap:
  default_nside:   128
  credible_level:  0.95

mcmc:
  walkers:         32
  steps:           2000
  burnin:          100
  thin_by:         10
  prior_h0_min:    10.0
  prior_h0_max:    200.0
  prior_alpha_min: -1.0
  prior_alpha_max: 1.0

cosmology:
  sigma_v_pec:     250.0
  c_light:         299792.458
  omega_m:         0.31

fetcher:
  cache_dir_name:  pesummary_cache
  timeout:         30
  max_retries:     3

# Computation settings
computation:
  backend: "auto" # Options: "auto", "numpy", "jax"

# Redshift marginalization settings for likelihood computation
redshift_marginalization:
  z_err_threshold: 1e-6   # Threshold below which to skip marginalization (essentially zero uncertainty)
  n_quad_points: 7        # Number of Gaussian quadrature points for integration
  sigma_range: 4.0        # How many sigma to integrate over in redshift space

# MCMC initial position settings
mcmc_initial_positions:
  h0_mean: 70.0    # Mean H0 value for walker initialization (km/s/Mpc)
  h0_std: 10.0     # Standard deviation for H0 walker initialization
  alpha_mean: 0.0  # Mean alpha value for walker initialization
  alpha_std: 0.5   # Standard deviation for alpha walker initialization

# Example settings for combining multiple events
multi_event_analysis:
  run_settings:
    run_label: "demo_run"
    base_output_directory: "output/multi_event_runs/"
    candidate_galaxy_cache_dir: "cache/candidate_galaxies/"
    gw_posteriors_cache_dir: "cache/gw_posteriors/"
  events_to_combine:
    - event_id: "GW170817"
    - event_id: "GW190814"
  priors:
    H0: { min: 10.0, max: 200.0 }
    alpha: { min: -2.0, max: 2.0 }
  mcmc:
    n_walkers: 10
    n_steps: 250
    burnin: 100
    thin_by: 10
    initial_pos_config:
      H0: { mean: 70.0, std: 5.0 }
      alpha: { mean: 0.0, std: 0.2 }
  cosmology:
    sigma_v_pec: 300.0
